### ISSUE TITLE
What to do with replication lag graphing

### ISSUE THREAD

**Issue by hwine** [hwine/innodb-cutover#10]
This was set up temporarily running in a screen session on bm81. Options include:
- discard
- save scripts, but don't leave running
- make them real (puppet controlled)

I'm not sure how much value they have.

**Comment by catlee** [comment]
Once we figured out the innodb vs myisam differences, did these give us value over what the data team's checks provide?

**Comment by hwine** [comment]
I believe the scripts used for this cutover:
- gave us confidence (independent opinion) on accuracy of data team's check
- showed the 'minute by minute' lag. The graphs show that there can be significant temporary lags -- most commonly around when the data team's checksums are running. 😄 

I think running them manually might have value when doing a planned fail over. They would show that replication has caught up after all writers are suspended. This was [step 110](http://innodb-cutover.readthedocs.io/en/latest/plan_diag.html) during this TCW.

Keeping them around would have the best chance of being valuable if we commit to creating the procedure for database failover (on the releng side) -- which clients need to be restarted, etc.

@MihaiTabara -- I believe you ran the scripts manually during the TCW. Any comments or corrections?

**Comment by MihaiTabara** [comment]
@hwine I feel strong about your last-first argument: "gave us confidence (independent opinion) on accuracy of data team's check". For me at least, it was a good metric to make sure that step was completed.

I'd be in favor of running them manually whenever we'll be doing planned fail over. Useful stuff, why ditch them? :)

**Comment by hwine** [comment]
This code has been committed on the 2016-10-08_TCW branch. See [script](https://github.com/mozilla-releng/TCW-history/blob/2016-10-08_TCW/monitor_replication.py).
