### ISSUE TITLE
Soft or Hard Tree Closure?

### ISSUE THREAD

**Issue by hwine** [hwine/innodb-cutover#12]
Per GPS, we should be okay with just setting hg.m.o to [read only](https://mozilla-version-control-tools.readthedocs.io/en/latest/hgmo/ops.html). That will impact any pushes (including tag setting), but allow most automation.

This would be the first time using this procedure in a TCW.

**Comment by hwine** [comment]
@klibby any concerns about setting "read only" given the nature of the work to be done?

**Comment by klibby** [comment]
No concerns!
