### ISSUE TITLE
Prevent new AWS instances during TCW

### ISSUE THREAD

**Issue by nthomas-mozilla** [hwine/innodb-cutover#17]
During the 2017-01-11 TCW we had ~700 pending jobs after the buildbot masters were shut down. eg 

$ grep 'processing [0-9]* pending jobs'  aws_watch_pending.log.1
...
2017-02-11 07:50:03,113 - processing 70 pending jobs
2017-02-11 07:55:02,631 - processing 54 pending jobs
2017-02-11 08:00:02,896 - processing 104 pending jobs
2017-02-11 08:05:02,112 - processing 48 pending jobs
2017-02-11 08:10:03,068 - processing 46 pending jobs
2017-02-11 08:15:02,459 - processing 49 pending jobs
2017-02-11 08:20:03,064 - processing 662 pending jobs
2017-02-11 08:25:02,440 - processing 714 pending jobs
2017-02-11 08:32:02,203 - processing 714 pending jobs
2017-02-11 08:35:02,233 - processing 714 pending jobs
2017-02-11 08:40:02,835 - processing 714 pending jobs

So it started instances, but no masters were up to run the jobs, so we started more instances, until we hit our limits. ---> Unnecessary dollars spent on AWS compute.

Now that slavealloc is backup, the aws_stop_idle.py script is cleaning them up.

**Comment by hwine** [comment]
@nthomas-mozilla What's the action here? 
 - Do we have existing documentation on how to do this?
 - Do we need to create the docs & a wrapper script?

**Comment by nthomas-mozilla** [comment]
No docs that I know of. The cron job runs on aws-manager2, defined in puppet at [modules/aws_manager/manifests/cron.pp](https://hg.mozilla.org/build/puppet/file/default/modules/aws_manager/manifests/cron.pp#l23). Might be as simple as disabling that, and forcing puppet to run.

**Comment by rail** [comment]
we can temporarily set the global limits in https://github.com/mozilla-releng/build-cloud-tools/blob/master/configs/watch_pending.cfg#L230-L239 to 0 for all types and backout after we are done.

**Comment by nthomas-mozilla** [comment]
That's a much better idea!

**Comment by hwine** [comment]
@rail Great! A couple of follow on questions:
 - how do those changes get deployed?
 - how long before they become effective? _(e.g. would we throttle 2 hr in advance of a TCW)_

**Comment by rail** [comment]
aws-manager pulls the changes every 5 minutes from the master branch of this repo: https://hg.mozilla.org/build/puppet/file/tip/modules/aws_manager/manifests/cron.pp#l209

**Comment by hwine** [comment]
@rail more questions:
1. Are the travis results reported to #releng?
2. Is the deployment of changes reported to #releng?

If not, how else can I be sure the change has deployed successfully?

**Comment by rail** [comment]
1. It doesn't look like we have notifications enabled for this repo. Shouldn't be hard to do, similar to https://github.com/mozilla/build-tools/blob/master/.travis.yml#L34-L42
2. The puppet manifest looks too simple, I don't think we report. We can probably come up with better plan for this. Maybe create "production" branch, limit it to releng-only, merge when want to deploy?

**Comment by hwine** [comment]
@rail - great long term plans, AND is there anything I could do today to confirm syntax & deployment?

**Comment by hwine** [comment]
In the meantime, the contents of the file:
```
    aws-manager:/builds/aws_manager/cloud-tools/configs/watch_pending.cfg
```
can be monitored (updated via cron job)

**Comment by hwine** [comment]
Opened [bug 1343397](https://bugzilla.mozilla.org/show_bug.cgi?id=1343397) for follow on actions.
