### ISSUE TITLE
Needed to reboot windows test machines

### ISSUE THREAD

**Issue by hwine** [hwine/innodb-cutover#18]
Per philor in #releng:
whenever anything makes slavealloc unavailable, like it was, someone needs to be on the hook to reboot every Windows test slave that rebooted while it was down, because that gives them the never-get-overs

**Comment by nthomas-mozilla** [comment]
We should check if we're using runner on those machines, as that picked up a lot of mac slaves which had the same problem. It was basically cycling them through the tasks.

**Comment by hwine** [comment]
What are the next steps here? My guess:

- figure proper workaround for next TCW
  - is there something that should be shut down prior to BB being shut down?
  - is there a post TCW manual step that is needed
 - see if ``runner`` is used on the Windows test boxes:
   - if so: file ticket to debug why they didn't do the right thing
   - if not: file ticket to add ``runner`` or otherwise "self heal"

@nthomas-mozilla can you confirm, please?

**Comment by hwine** [comment]
Is this related to #6?

**Comment by nthomas-mozilla** [comment]
It is related to #6 in the sense that workers need to reconnect, but without investigating further I don't know if windows workers handle the 'no response from slavealloc' case the same as 'the buildbot-masters went on holiday and didn't take me too, hrrrmmmph'.

**Comment by hwine** [comment]
Closing here, moving finding a solution to https://bugzil.la/1340716
