### ISSUE TITLE
Exceptions during buildbot-masters stop

### ISSUE THREAD

**Issue by MihaiTabara** [hwine/innodb-cutover#4]
Not sure if any of the following is relevant but I thought we should I should at least mention them.

[buildbot-master109.bb.releng.scl3.mozilla.com] put: /home/buildduty/buildduty-tools/repos/tools/buildfarm/maintenance/buildbot-wrangler.py -> /builds/buildbot/tests1-windows/buildbot-wrangler.py
[buildbot-master109.bb.releng.scl3.mozilla.com] run: python buildbot-wrangler.py stop /builds/buildbot/tests1-windows/master
[buildbot-master109.bb.releng.scl3.mozilla.com] out: 2016-10-08 06:38:49-0700 [-] Unhandled Error
[buildbot-master109.bb.releng.scl3.mozilla.com] out:    Traceback (most recent call last):
[buildbot-master109.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/internet/base.py", line 796, in runUntilCurrent
[buildbot-master109.bb.releng.scl3.mozilla.com] out:        call.func(_call.args, *_call.kw)
[buildbot-master109.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/buildbot-0.8.2_hg_8b87b4974e3c_production_0.8-py2.7.egg/buildbot/process/buildstep.py", line 204, in _finished
[buildbot-master109.bb.releng.scl3.mozilla.com] out:        d.addBoth(self.deferred.callback)
[buildbot-master109.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/internet/defer.py", line 283, in addBoth
[buildbot-master109.bb.releng.scl3.mozilla.com] out:        callbackKeywords=kw, errbackKeywords=kw)
[buildbot-master109.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/internet/defer.py", line 249, in addCallbacks
[buildbot-master109.bb.releng.scl3.mozilla.com] out:        self._runCallbacks()
[buildbot-master109.bb.releng.scl3.mozilla.com] out:    --- <exception caught here> ---
[buildbot-master109.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/internet/defer.py", line 441, in _runCallbacks
[buildbot-master109.bb.releng.scl3.mozilla.com] out:        self.result = callback(self.result, _args, *_kw)
[buildbot-master109.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/internet/defer.py", line 318, in callback
[buildbot-master109.bb.releng.scl3.mozilla.com] out:        self._startRunCallbacks(result)
[buildbot-master109.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/internet/defer.py", line 410, in _startRunCallbacks
[buildbot-master109.bb.releng.scl3.mozilla.com] out:        raise AlreadyCalledError
[buildbot-master109.bb.releng.scl3.mozilla.com] out:    twisted.internet.defer.AlreadyCalledError:
[buildbot-master109.bb.releng.scl3.mozilla.com] out: 

[OK] stopped buildbot-master109.bb.releng.scl3.mozilla.com:/builds/buildbot/tests1-windows

---

[buildbot-master110.bb.releng.scl3.mozilla.com] put: /home/buildduty/buildduty-tools/repos/tools/buildfarm/maintenance/buildbot-wrangler.py -> /builds/buildbot/tests1-windows/buildbot-wrangler.py
[buildbot-master110.bb.releng.scl3.mozilla.com] run: python buildbot-wrangler.py stop /builds/buildbot/tests1-windows/master
[buildbot-master110.bb.releng.scl3.mozilla.com] out: 2016-10-08 06:39:16-0700 [Broker,31889,10.26.41.250] Unhandled Error
[buildbot-master110.bb.releng.scl3.mozilla.com] out:    Traceback (most recent call last):
[buildbot-master110.bb.releng.scl3.mozilla.com] out:    Failure: twisted.spread.pb.PBConnectionLost: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
[buildbot-master110.bb.releng.scl3.mozilla.com] out:    ]
[buildbot-master110.bb.releng.scl3.mozilla.com] out: 2016-10-08 06:39:16-0700 [Broker,31889,10.26.41.250] Unhandled Error
[buildbot-master110.bb.releng.scl3.mozilla.com] out:    Traceback (most recent call last):
[buildbot-master110.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/internet/defer.py", line 363, in unpause
[buildbot-master110.bb.releng.scl3.mozilla.com] out:        self._runCallbacks()
[buildbot-master110.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/internet/defer.py", line 441, in _runCallbacks
[buildbot-master110.bb.releng.scl3.mozilla.com] out:        self.result = callback(self.result, _args, *_kw)
[buildbot-master110.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/internet/defer.py", line 397, in _continue
[buildbot-master110.bb.releng.scl3.mozilla.com] out:        self.unpause()
[buildbot-master110.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/internet/defer.py", line 363, in unpause
[buildbot-master110.bb.releng.scl3.mozilla.com] out:        self._runCallbacks()
[buildbot-master110.bb.releng.scl3.mozilla.com] out:    --- <exception caught here> ---
[buildbot-master110.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/internet/defer.py", line 441, in _runCallbacks
[buildbot-master110.bb.releng.scl3.mozilla.com] out:        self.result = callback(self.result, _args, *_kw)
[buildbot-master110.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/spread/pb.py", line 763, in serialize
[buildbot-master110.bb.releng.scl3.mozilla.com] out:        return jelly(object, self.security, None, self)
[buildbot-master110.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/spread/jelly.py", line 1122, in jelly
[buildbot-master110.bb.releng.scl3.mozilla.com] out:        return _Jellier(taster, persistentStore, invoker).jelly(object)
[buildbot-master110.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/spread/jelly.py", line 475, in jelly
[buildbot-master110.bb.releng.scl3.mozilla.com] out:        return obj.jellyFor(self)
[buildbot-master110.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/spread/flavors.py", line 127, in jellyFor
[buildbot-master110.bb.releng.scl3.mozilla.com] out:        return "remote", jellier.invoker.registerReference(self)
[buildbot-master110.bb.releng.scl3.mozilla.com] out:      File "/builds/buildbot/tests1-windows/lib/python2.7/site-packages/twisted/spread/pb.py", line 658, in registerReference
[buildbot-master110.bb.releng.scl3.mozilla.com] out:        luid = self.luids.get(puid)
[buildbot-master110.bb.releng.scl3.mozilla.com] out:    exceptions.AttributeError: 'NoneType' object has no attribute 'get'
[buildbot-master110.bb.releng.scl3.mozilla.com] out: 

[OK] stopped buildbot-master110.bb.releng.scl3.mozilla.com:/builds/buildbot/tests1-windows

**Comment by hwine** [comment]
@MihaiTabara - go ahead and close if this is "known & okay-ish". If we still need an answer, please add the "Question" label
