### ISSUE TITLE
Check command queue emptiness fabric new action

### ISSUE THREAD

**Issue by MihaiTabara** [hwine/innodb-cutover#5]
Nick pulled up a quick action in fabric to check that. In my opinion it'd be useful to land it as it might be useful for future use. He pasted in a pastebin but since I don't know the expiration date for that, I moved the code to a gist just in case.

nthomas++
https://gist.githubusercontent.com/MihaiTabara/f1b51d213ca2a0d104f76e91432b6e35/raw/6924f8d997e4be7bfc4a484747884561615ce4f9/gistfile1.txt

**Comment by hwine** [comment]
moved to [bug 1312509](https://bugzil.la/1312509)
