### ISSUE TITLE
Missed difference in MyISAM vs. InnoDB behavior

### ISSUE THREAD

**Issue by hwine** [hwine/innodb-cutover#8]
Per [bug 1308818](https://bugzil.la/1308818) we stumbled on a behavioral difference between MyISAM & InnoDB. Given a key longer than column width, MyISAM truncates silently & continues. InnoDB throws an error.
## Actions taken and needed:
- [X] [bug 1308932](https://bugzil.la/1308932) - code changed to truncate before hitting DB
- [x] [bug 1308818](https://bugzil.la/1308818) - database column to be widened
- [x] [bug 1308957](https://bugzilla.mozilla.org/show_bug.cgi?id=1308957) - code to be changed to truncate before hitting DB
- [x] do we need to look for any other possible suspect columns?

**Comment by hwine** [comment]
From the cutover process point of view, I think we are okay with this. The goal was to be somewhat aggressive and fail forward.

What is less clear to me is if we can/should/must have a script to test this during any future maintenance.

**Comment by nthomas-mozilla** [comment]
[bug 1308957](https://bugzilla.mozilla.org/show_bug.cgi?id=1308957) is another example of 'error instead of truncation'.

**Comment by hwine** [comment]
I believe [bug 1308932](https://bugzil.la/1308932) is another case. (Thanks to @Callek for that one) -- adding a checklist to initial comment

**Comment by catlee** [comment]
This was pretty important - and too bad we didnt' know ahead of time, we probably could have checked for places where we were being silently truncated.

**Comment by hwine** [comment]
Filed [bug 1312505](https://bugzil.la/1312505) to discover other columns.

**Comment by hwine** [comment]
All work completed.
