### ISSUE TITLE
Should we try this approach next TCW?

### ISSUE THREAD

**Issue by hwine** [hwine/innodb-cutover#9]
If so, the repo should probably be moved to mozilla-releng, and have a standard name.

We could have one repo, with "next tcw" as default branch (somewhat similar to release warrior), or one repo per TCW, and delete older ones after 3 months.

I think I vote for just one repo, so we can keep the docs in one spot. If you agree, give this comment a thumbs up reaction.

**Comment by catlee** [comment]
Do you mean for handling the distributed post-mortem?

**Comment by hwine** [comment]
@catlee yes -- but for more than just the post mortem. 
- This repo also has the cross team interactions (not needed for all TCW).
- It would be the historical archive of what issues arose with prior TCWs
- It would be the place to have process-enhancement tickets.
- It would make sense to move the [process docs](http://moz-releng-docs.readthedocs.io/en/latest/procedures/index.html) here as well.

**Comment by hwine** [comment]
Decision: try for [2016-11-19 TCW](https://github.com/mozilla-releng/TCW-history/wiki/2016-11-19-TCW)
